add stateful scheduled task support
yoomoney/db-queue-scheduler pull request #11
Opened 2021-11-17 11:01 UTC by ul8422

2021-11-17 21:22 UTC, layfe commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/ScheduledTaskDefinition.java
> +    private final StatefulScheduledTask statefulScheduledTask;
как то объединить под один интерфейс не получится? 
совсем не красивая обработка будет? 
наверное, с 17 java и sealed классами + switch можно будет красиво сделать...

2021-11-17 21:31 UTC, layfe commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueue.java
> +        String payload = taskDefinition.getStatefulScheduledTask()
хм. здесь будет один и тот же код для обычных и stateful классов, и выполняться в зависимости от optional будет, или неправильно понимаю?

если так - то мне кажется, обычно в таких случаях 
1. определяют возможные типы (stateful, stateless)
2. делают метод getType
3. и делают обработчик отдельно для типа if (getType == stateful) definition.orElseThrow

мне кажется так более расширяемо. сейчас 2 поля разных, а если будет 5? 
легче документировать, быстрее упадем при ошибке (будет orElseThrow, а не optional), код понятней, что к какому типу относится

2021-11-18 07:12 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/ScheduledTaskDefinition.java
> +    private final StatefulScheduledTask statefulScheduledTask;
Со стороны открытого API я исходил из удобства использования
- В `stateless` и `steteful` задачах отличается контракт вызова как в аргументах, так и в возвращаемом типе
- Не хотелось давать пользователю видеть ~лишние методы, усложнять код дженериками итд c одной стороны, а с другой оставить простоту и ясность API. 

Пример метода stateless задачи:
```java
    @Override
    public ScheduledTaskExecutionResult execute() {
        return ScheduledTaskExecutionResult.success();
    }
```

Пример метода stateful задачи:
```java
    @Override
    public StatefulScheduledTaskExecutionResult<State> execute(@Nullable State state) {
        // возвращаемый тип изменен с целью требовать вернуть state
        return StatefulScheduledTaskExecutionResult.success(state);
    }
```

Во внутренней части библиотеки
1) пробовал трансофрмировать stateless в statefull задачу, но результат показался запутанным для понимания.
2) вводить дополнительную абстракцию - исполнителя задач показалось оверинжинерингом;
3) на мой взгляд текущий вариант выглядит достаточно простым в понимании (для 2ух типов задач). + это internal


> как то объединить под один интерфейс не получится?
совсем не красивая обработка будет?

думаю нет/не вижу варианта лучше

2021-11-18 07:45 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueue.java
> +        String payload = taskDefinition.getStatefulScheduledTask()
Тут мы ставим задачу в `db-queue`. 
Для `db-queue` неважно какая это задача, библиотека принимает `payload`.

Диф показывает, что раньше мы всегда ставили пустую строку, а теперь еще смотрим нет ли initialValue.

2021-11-18 08:53 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/ScheduledTaskDefinition.java
> +    private final StatefulScheduledTask statefulScheduledTask;
Давайте очно на код посмотрим. Выглядит так, что задача без payload это частный случай, а не что-то отдельное.

2021-11-18 08:55 UTC, layfe commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueue.java
> +        String payload = taskDefinition.getStatefulScheduledTask()
точно

2021-11-18 12:08 UTC, f0y requested changes

2021-11-18 12:08 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/models/ScheduledTask.java
> +        return execute();
выглядит очень криво...

2021-11-18 16:15 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/models/ScheduledTask.java
> +        return execute();
замажорил либу, добавил контекст задачи

2021-11-19 09:10 UTC, f0y approved these changes

2021-11-19 10:52 UTC, layfe approved these changes

2021-11-19 15:08 UTC, merged