add `FailRetryType.NONE`, `FailureSettings.maxAttempts` settings
yoomoney/db-queue-scheduler pull request #12
Opened 2021-11-25 20:24 UTC by ul8422

2021-11-26 07:26 UTC, f0y requested changes

2021-11-26 07:26 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/settings/ScheduleSettings.java
> +     *  <pre>
javadoc нормально отображается? Всё таки дока над приватными полями

2021-11-26 07:26 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
У меня не получилось понять для чего это нужно

2021-11-26 07:32 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/settings/ScheduleSettings.java
> +     *  <pre>
Ты конкретно про этот джавадок?
- да,
- это публичный метод

Вот текущий джавадок:
https://www.javadoc.io/doc/ru.yoomoney.tech/db-queue-scheduler-core/latest/ru/yoomoney/tech/dbqueue/scheduler/settings/ScheduleSettings.html

2021-11-26 07:41 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
- предотвращает выполнение таски от повторного выполнения в случае ее длительной обработки;
- раньше это контролировалось через `FailureSettings`. но это 1) добавляет шанс мис конфигурации 2) не дает создавать задачи без дожатия в случае ошибок;
- на этот кейс написал тест

или ты имеешь ввиду что не понятно по коду и нужно понятнее написать? :/

2021-11-26 07:53 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
Мне и так и так было непонятно. По коду надо написать для чего это нужно, а то кирпички то сложили, а цели не ясны. 

Почему HEARTBEAT_INTERVAL.multipliedBy(2L) ?

2021-11-26 08:04 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
> Почему HEARTBEAT_INTERVAL.multipliedBy(2L) ?
- с целью не "проспать" следующую попытку переноса задачи
- почему `*2`, а не `+1` - не вижу критичности в интервале переноса (пока это интервал меньше ~часа). `*2` мне показалось нагляднее

> Мне и так и так было непонятно. По коду надо написать для чего это нужно, а то кирпички то сложили, а цели не ясны.

ок, понял

2021-11-26 08:30 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
> пока этот интервал меньше ~часа

А откуда такое условие? 

В целом объяснение мне не понятно.

2021-11-26 09:08 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
> А откуда такое условие?
> В целом объяснение мне не понятно.

Алгоритм работы:

1. `db-queue consumer` берет задачу;
2. `db-queue` откладывает повторное выполнение при выборе задачи, согласно настройкам очереди; 
3. `db-queue consumer` начинает обработку периодической задачи;
4. при завершении обработки периодической задачи, мы меняем дату следующего запуска в `db-queue` согласно настройкам (`FailureSettings` и `ScheduleSettings`). т.е. настройки повторов задачи `db-queue` мы переопределяем.

В чем проблема:

1. `db-queue` не продлевает ~блокировку задачи. Это значит, что если обработка задачи продолжительная по времени, то возможна ситуация, когда `db-queue-consumer` другой ноды начнет выполнять задачу повторно - т.к. время на которое перенесли задачу на шаге 2 наступило, но по факту задача еще выполняется.
2. С этой целью добавлен `HeartbeatAgent` - он продлевает ~блокировку и может влиять на повтор выполнения задачи только в случае когда JVM процесс убит и библиотека не успела записать новый интервал в БД .
3. В таком случае считаю(считал), что задача должна выполняться повторно другой нодой без задержек.

Хотя думаю в таком кейсе есть шанс положить все ноды: задача падает по OOM и кладет все ноды каскадом например. Поправлю на ~`Max(2*heartbeatInterval, failRetryInterval)`

2021-11-26 12:18 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
Нельзя сказать что это какое-то очевидное поведение. Кажется что в таком случае нужно сообщать о таком случае, поскольку есть проблема с конфигурацией очереди.

2021-11-26 13:04 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
Время выполнения задачи зависит от внешних факторов. сегодня задача выполнилась за минуту, а через месяц стала выполняться за час(бд, сеть, диск итд). Сообщить я могу,  но это сильно поздно будем - когда одновременное выполнение случится на проде например.

2021-11-26 13:08 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
Если задача переставляется по механизму hearbeat, то надо логировать. Я не считаю это стандартной ситуацией. А ты что думаешь?

2021-11-26 13:29 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
- если мы рассматривает настройки повтора задачи как максимальное время ее выполнения, то ты прав;
- если у нас настройки ретрая это только задержка между последним неудачным запуском и следующим, то переставление задачи по heartbeat-у штатная ситуация

На мой взгляд первый вариант не очевиден

2021-11-26 13:53 UTC, f0y commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
Понял тебя. Тогда следующий вопрос - зачем прогрессивное откладывание? Почему нельзя чекать задачу раз в 10 секунд? Почему это не конфигурируется? Почему в документации об этой логике ничего не написано?

2021-11-26 15:15 UTC, ul8422 commented on db-queue-scheduler-core/src/main/java/ru/yoomoney/tech/dbqueue/scheduler/internal/queue/ScheduledTaskQueueConsumer.java
> +        this.heartbeatAgent = new HeartbeatAgent(
> Тогда следующий вопрос - зачем прогрессивное откладывание?

Установив пргрессивное откладваение мы не будем грузить упавший сервис с фиксированно-малой задержкой (например)

> Почему нельзя чекать задачу раз в 10 секунд? Почему это не конфигурируется? 

Старался выносить в публичные настройки минимум параметров. т.к. 1) меньше настроек - легче разобраться, быстрее сконфигурировать (имхо) 2) добавить легче, чем удалить - добавляем минором, а удаляем мажором.

> Почему в документации об этой логике ничего не написано?

О логике дожатия задач? Распишу

2021-11-29 10:25 UTC, f0y approved these changes

2021-11-30 12:33 UTC, f0y approved these changes

2021-12-01 07:54 UTC, f0y approved these changes

2021-12-02 09:25 UTC, merged