Upgrade to Spring Boot 2.6.4
yoomoney/db-queue-scheduler pull request #15
Opened 2022-03-11 16:54 UTC by layfe

2022-03-14 09:32 UTC, f0y requested changes

2022-03-14 09:32 UTC, f0y commented on CHANGELOG.md
> +* Upgrade to Spring Boot 2.6.4
Аналогичные замечания как для db-queue

2022-03-14 13:47 UTC, ul8422 approved these changes, later dismissed

2022-03-17 15:58 UTC, layfe commented on CHANGELOG.md
> +* Upgrade to Spring Boot 2.6.4
обновила

2022-03-18 06:45 UTC, ul8422 approved these changes

2022-03-18 07:50 UTC, f0y approved these changes

2022-03-18 07:50 UTC, merged